### ISSUE TITLE
Replay strings parsing is wrong

### ISSUE THREAD

**Issue by Katharsas** [FAForever/faf-java-commons#28]
```java
  private String readString(LittleEndianDataInputStream dataStream) throws IOException {
    StringBuilder stringBuilder = new StringBuilder();
    char character;
    while ((character = (char) dataStream.readByte()) != 0) {
      stringBuilder.append(character);
    }
    return stringBuilder.toString();
  }
```
in `ReplayDataParser` cannot deal with UTF8/UTF16 (whatever th actual encoding is).

Probably cause for https://github.com/FAForever/downlords-faf-client/issues/1395

**Comment by Wesmania** [comment]
Confirming that replay strings are encoded in UTF-8.

**Comment by Wesmania** [comment]
According to Askaholic some replays in 1.2-1.4M range have non-UTF-8 encodings (currently we're at 10M). I didn't verify, but most replays should be be in UTF-8 now.

**Comment by Katharsas** [comment]
Are we really sure that strings are actually encoded in UTF-8 mostly? If strings are encoded in extended ASCII, they will look like valid UTF-8 as long as no chars from the extension are used. But in that case, two persons with two different extensions should have problems with chatting directly ingame already.

I mean we can just assume UTF-8 and check if the russian chat from replay 10084790 gets decoded correctly.

And (if UTF-8 is the most used encoding) we probably need to catch decode/encode Exceptions and maybe create a replacement chat message like "\<encoding not supported>" when non-UTF-8 chat messages are displayed or something. Unless anybody wants to go down the route of encoding detection, which we probably don't want to.

**Comment by Wesmania** [comment]
We saw at least one case where a message was *almost* valid UTF-8, but had one extra escape character, probably from a broken translation string. Whatever method is used should account for that and display what it can.
