### ISSUE TITLE
Support transitional zstd replay compression

### ISSUE THREAD

**Issue by Wesmania** [FAForever/faf-java-commons#32]
See https://github.com/FAForever/downlords-faf-client/issues/1374.

**Comment by Brutus5000** [comment]
The parsing of the JSON head and the decompression is handled in the client:
https://github.com/FAForever/downlords-faf-client/blob/develop/src/main/java/com/faforever/client/replay/ReplayFileReaderImpl.java

We might want to put it into commons. I'm not sure.

**Comment by Wesmania** [comment]
The intention was to abstract it away, yeah. Now that we have multiple formats and some decompression work is done in commons anyway, I think it's the better solution.

**Comment by Wesmania** [comment]
Of course it's another matter entirely if anything else than the client will actually use these decompressing functions. Maybe some replay analysis tools? The are some replay analysing functions in commons, so I guess something uses them?

**Comment by Brutus5000** [comment]
Implemented in #44
