### ISSUE TITLE
Restore game session message is not sent correctly

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/faf-java-commons#87]
Calling `FafLobbyClient.restoreGameSession` doesn't send the correct `restore_game_session` command to the server. Due to this, all ice reconnects have been failing for the past half year, as no game session is restored after reconnect and therefore no ice messages are forwarded.

**Comment by Sheikah45** [comment]
The  `restore_game_session` command has the correct format. The server only expects a single field `game_id` in the "restore_game_session" command so I do not see any incorrect formatting here.

Please be more specific what you think the error is.

**Comment by Sheikah45** [comment]
Issue is not this repository. Client was never sending the message https://github.com/FAForever/downlords-faf-client/pull/2681
